=== sondahi/gMyHealthyLife/server/temp/configuration/bin/resources/xml/adminfilemenulinks.dtd
<?xml version="1.0" encoding="UTF-8"?> <!-- XML değil, W3.org dan detaylara bakılabilir. veri haberleşmesi yaparsak detaylara ihtiyaç var mesela null girmeyin şu olacak vs.-->
<!ELEMENT menu (link*)> <!--!ELEMENT eleman tanımlıyorum, menu eleman ismi, (link* bir veya çok ? olursa sıfır yada bir detaylara bakarsın) içerik: içerik texte olabilir başka elemanlarda -->
<!ELEMENT link (name,url)> <!-- name ve url olacak-->
<!ATTLIST link id CDATA #REQUIRED> <!-- unique id olacak, CDATA text ID dersek sadece int gerekiyor, required olmak zorunda -->
<!ELEMENT name (#PCDATA)>
<!ELEMENT url (#PCDATA)>

=== sondahi/gMyHealthyLife/server/temp/configuration/bin/resources/xml/adminfilemenulinks.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE menu SYSTEM "adminfilemenulinks.dtd"> <!-- instruction process veri transferi yapmayacağımız sadece menu linkleri yazacağımız için dtd yeterli, DTD kullanmayacağım.-->
<menu>
    <link id="home">
        <name>HOME PAGE</name> <!-- sıralama bile önemli-->
        <url>home.jsp</url>
    </link>
    <link id="food">
        <name>FOODS</name>
        <url>food.jsp</url>
    </link>
    <link id="message">
        <name>MESSAGE</name>
        <url>message.jsp</url>
    </link>
    <link id="mail">
        <name>MAIL</name>
        <url>mail.jsp</url>
    </link>
</menu>
